# Generated by Django 3.2.7 on 2021-10-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=50, unique=True)),
                ('Firstname', models.CharField(default='', max_length=30)),
                ('Lastname', models.CharField(default='', max_length=30)),
                ('Email', models.EmailField(default='', max_length=254, unique=True)),
                ('Gender', models.CharField(default='', max_length=10)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('City', models.CharField(default='', max_length=30)),
                ('State', models.CharField(default='', max_length=30)),
                ('Region', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
