# Generated by Django 3.2.7 on 2021-10-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FTC_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='Gender',
        ),
    ]
