# Generated by Django 3.2.7 on 2021-10-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTC_users', '0002_auto_20211004_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='Gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
